# Generated by Django 2.2.7 on 2019-11-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='name',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='target',
        ),
    ]
