# Generated by Django 3.0.3 on 2020-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191126_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AddField(
            model_name='link',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
